### ISSUE TITLE
fix a bug 

### ISSUE THREAD

**Issue by Taraslut** [ValentynShvets/HomeWork#1]
There is a bug --> 
Number to move >> 3
Число 3 переміщено
15	14	13	12	
_______________
11	10	9	8	
_______________
7	6	5	4	
_______________
_	3	1	2	
_______________

Number to move >> 4
Число 4 переміщено
15	14	13	12	
_______________
11	10	9	8	
_______________
7	6	5	_	
_______________
4	3	1	2	
_______________

Number to move >> 

----- last move is unable -- you could not remove 4 in free space. 
you mast fix it

**Comment by ValentynShvets** [comment]
i fixed bug

**Comment by Taraslut** [comment]
Resolved
